# Generated by Django 3.2.15 on 2022-11-20 08:41

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0039_alter_order_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='order',
            managers=[
                ('custome_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
