# Generated by Django 3.2.15 on 2022-11-20 13:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0040_alter_order_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='productorder',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=99, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Фиксированная цена продукта'),
        ),
    ]
