# Generated by Django 3.2.15 on 2022-11-20 13:48

from django.db import migrations


def copy_prices(apps, schema_editor):
    product_order_model = apps.get_model(
        'foodcartapp',
        'ProductOrder',
    )
    product_model = apps.get_model(
        'foodcartapp',
        'Product',
    )

    for product in product_model.objects.all().iterator():
        product_order_model.objects.filter(
            product_id=product.id,
        ).update(price=product.price)


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0041_productorder_price'),
    ]

    operations = [
        migrations.RunPython(copy_prices)
    ]
