# Generated by Django 3.2.15 on 2022-11-21 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0042_migration_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('GT', 'Заказ принят в обработку'), ('PA', 'На сборе'), ('DE', 'Отдано курьеру'), ('FI', 'Заказ доставлен и закончен')], default='GT', max_length=2),
        ),
    ]
