# Generated by Django 3.2.15 on 2022-11-21 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0043_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('GT', 'Заказ принят в обработку'), ('PA', 'На сборе'), ('DE', 'Отдано курьеру'), ('FI', 'Заказ доставлен и закончен')], db_index=True, default='GT', max_length=2),
        ),
    ]
