# Generated by Django 3.2.15 on 2022-11-23 08:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0045_order_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='called_at',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='Called at'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivered_at',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='Delivered at'),
        ),
        migrations.AddField(
            model_name='order',
            name='registrated_at',
            field=models.DateField(db_index=True, default=django.utils.timezone.now, verbose_name='Registrated at'),
        ),
    ]
