# Generated by Django 3.2.15 on 2022-11-23 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0046_auto_20221123_0851'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pay_method',
            field=models.CharField(choices=[('IC', 'Наличными'), ('WC', 'Карточкой')], db_index=True, default='IC', max_length=2),
        ),
    ]
